import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/app/components/ui/sidebar";
import { AppSidebar } from "@/app/components/app-siderbar";

import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="h-full min-h-screen w-full p-4">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
